<?xml version="1.0" encoding="utf-8"?>
<Database Name="damaslighting" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=infobahn-consul;Initial Catalog=damaslighting;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="damaslightingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdminLogin" Member="AdminLogins">
    <Type Name="AdminLogin">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>