<%@ Page Language="C#" MasterPageFile="~/controlpanel/MasterPage.master" AutoEventWireup="true"
    CodeFile="ad_image.aspx.cs" Inherits="ad_image" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder_header" runat="Server">
    Image Gallery
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder_body" runat="Server">
            <table align="left" cellpadding="0" cellspacing="5" style="width: 100%">
                <tr>
                    <td align="left" valign="top" width="20%">
                        &nbsp;
                    </td>
                    <td style="width: 1px">
                        &nbsp;
                    </td>
                    <td align="left" valign="top" width="87%">
                        <asp:Label ID="lbl_msg" runat="server" ForeColor="#FF3300"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td>
                        Title
                    </td>
                    <td>
                        :
                    </td>
                    <td><asp:TextBox ID="txttitle" runat="server" CssClass="txtbox" Width="300px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        Image
                    </td>
                    <td>
                        :
                    </td>
                    <td><asp:FileUpload ID="FileUpload1" runat="server" CssClass="txtbox" />&nbsp;<asp:RequiredFieldValidator
                                        ID="RequiredFieldValidator1" runat="server" ControlToValidate="FileUpload1" ValidationGroup="1"
                                        ErrorMessage="*"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;
                    </td>
                    <td>
                        &nbsp;
                    </td>
                    <td>
                    <asp:Button ID="Button1" runat="server" Height="23px" OnClick="Button1_Click" Text="Submit"
																	Width="59px" ValidationGroup="1" />
															&nbsp;
																<asp:Button ID="Button2" runat="server" Height="23px" OnClick="Button2_Click" Text="Update"
																	Width="59px" />
															&nbsp;
																<asp:Button ID="Button3" runat="server" Height="23px" OnClick="Button3_Click" Text="Cancel"
																	Width="59px" />
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True"
								Font-Names="Verdana" Font-Size="11px" OnPageIndexChanging="GridView1_PageIndexChanging"
								OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="False" AutoGenerateSelectButton="True"
								OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="100%" CellPadding="4" 
                                ForeColor="#333333" GridLines="none">
								<RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
								<Columns>
									<asp:BoundField HeaderText="Image Name" DataField="title" HeaderStyle-HorizontalAlign="Left">
										<HeaderStyle HorizontalAlign="Left"></HeaderStyle>
									</asp:BoundField>
									<asp:TemplateField HeaderText="Image" HeaderStyle-HorizontalAlign="Left">
										<ItemTemplate>
											<asp:Label ID="lblid" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.imageid") %>'
												Visible="false"></asp:Label>
												<asp:Label ID="lblimg" runat="server" Text='<%# DataBinder.Eval(Container,"DataItem.img") %>'
												Visible="false"></asp:Label>
											<a href="../img_small/<%# DataBinder.Eval(Container,"DataItem.img") %>"
												target="_blank" target="_blank">
												<img id="img1" src="../img_small/<%# DataBinder.Eval(Container,"DataItem.img") %>" width="45px;" height="45px;" /></a>
										</ItemTemplate>
										<HeaderStyle HorizontalAlign="Left"></HeaderStyle>
									</asp:TemplateField>
								</Columns>
							    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                <EditRowStyle BackColor="#999999" />
                                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
							</asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;
                    </td>
                    <td>
                        &nbsp;
                    </td>
                    <td>
                        &nbsp;
                    </td>
                </tr>
            </table>
</asp:Content>
